# Numpy

https://numpy.org/

## What is it? 
- Numpy is a Python library used for working with arrays
- Numpy is the fundamental package for scientific computing in Python


## Why do we care? 
- Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
- Super fast. Numpy arrays are implemented in C, which makes numpy very fast.
- The arrays allows for vectorized operations

## Show us! 

### Create a 1D array

#### create a list
format: list()

In [1]:
#create a list
my_list = ['apple', 'banana', 'peach', 'plum']

In [2]:

my_list[0]


'apple'

In [3]:
my_list[1:]


['banana', 'peach', 'plum']

In [4]:

added_string = 'my favorite fruit is: '

In [6]:
[added_string + fruit for fruit in my_list]

#alternate is for loop

for fruit in my_list:

['my favorite fruit is: apple',
 'my favorite fruit is: banana',
 'my favorite fruit is: peach',
 'my favorite fruit is: plum']

In [13]:
#whats the type
type(my_list)
my_list = [1, 2, 3, 4]

In [12]:
for i in my_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [ ]:
#what is dtype

In [14]:
#whats the shape
len(my_list)

4

In [55]:
my_second_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [16]:
len(my_second_list)

3

In [17]:
for little_list in my_second_list:
    print(len(little_list))

3
3
3


#### create an array
format: np.array()

In [18]:
# importing numpy
import numpy as np

In [73]:
#create the array
#np.array?

my_array = np.array(my_list)
type(my_array)

numpy.ndarray

In [47]:
#create the array (from the contents of the list)
len(my_array)

4

In [48]:
#whats the type
type(my_array)

numpy.ndarray

In [49]:
#whats the shape
my_array.shape

(4,)

In [50]:
#dtype
my_array.dtype


dtype('int64')

#### access elements of our new array

#### slice the array

In [51]:
np.array(my_second_list).shape
#indexing my_array will be similar to the way we index a list

(3, 3)

In [52]:
my_array[0]

1

In [53]:
my_array[1:3]

array([2, 3])

In [35]:
my_array[:-1]

array([1, 2, 3])

#### create an array from 1 to 100

In [54]:
my_100 = np.array(range(1,101))

In [38]:
my_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

### Create a 2D array

In [72]:
#type
my_2d_array = [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]
my_2d_array = np.array(my_2d_array)
type(my_2d_array)


numpy.ndarray

In [58]:
my_2d_array[0][2]

3

In [63]:
# first half of indexing array will be for rows, other side will be for columns
#1,: or anything following a comma will pull the whole row or column
my_2d_array[1,:]

array([4, 5, 6])

In [ ]:
#type


#### access elements

### Descriptive Stats

In [ ]:
#pulling back my big array from 1 - 100


#### using methods: the method is called on the numpy object
format: object.method()

#### using functions: using numpy to call functions
np.function(object)

### Array of Booleans! 

### Boolean Masks

1. create an array
2. make a list of booleans (mask)
3. combine

    format: array [ list of booleans ] 

In [ ]:
#pull back our small array
my_array
# if listed
# thing for thing in my_100 if thing > 10

In [77]:
#make list of booleans aka our mask
my_over_ten_mask = my_100 > 10

# [ ] will now serve as a 'WHERE' condition

my_100[my_over_ten_mask]

# prints exclusively true values for boolean mask

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [80]:
# can be done with no variable:
# even elements in my array:
my_array[my_array % 2 == 0]

array([2, 4])

In [ ]:
#working with multiple conditions and limitations

my_array[(my_array % 2 == 0 ) and (my_array < 3)]




> only return values that are true. this is known as boolean masking

#### how else can we get our array of boolean values?

In [84]:
# can be accomplished with ' & ' operator

my_array[(my_array % 2 == 0 ) & (my_array < 3)]


array([2])

In [83]:
# OR operand can be expressed with ' | '

my_array[(my_array % 2 == 0 ) | (my_array < 3)]


array([1, 2, 4])

In [88]:
# using loops to iterate over arrays

# my_second_list + 5
# breaks

my_2d_array + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [90]:
# all false in operand returns an empty array
my_2d_array[(my_2d_array + 5) < 6]

array([], dtype=int64)

In [98]:
# can it be converted back to list?
#returns a list of arrays
list(my_2d_array)
new_list = []
for x in list(my_2d_array):
    new_list.append((list.x))

print(new_list)

AttributeError: type object 'list' has no attribute 'x'

In [101]:
my_list_plus_one = []
for i in my_list:
    my_list_plus_one.append(i+1)
print(my_list_plus_one)


[2, 3, 4, 5]


In [100]:
my_array + 1

array([2, 3, 4, 5])

In [103]:
%%timeit

UsageError: %%timeit is a cell magic, but the cell body is empty. Did you mean the line magic %timeit (single %)?


In [104]:
# format of numbers to remain int can use ' _ ' instead of ' , '

big_array = np.array(range(0,1_000_001))

#### what about with multiple conditions?

In [105]:
big_array ** 3
# using

array([                  0,                   1,                   8, ...,
        999994000011999992,  999997000002999999, 1000000000000000000])

#### do it with a matrix!

#### cool! can we just do it with a list instead of an array?

#### let's bring it back to arrays and make them bigger

#### what if the numbers are out of order?

> still works!

#### shortcut?

#### what if you put something that was all false, what would it return?

> an empty array

#### what if we wanted to check two conditions?

#### can we convert our arrays back to lists?

#### what if we wanted the opposite of our mask?

## Vectorization Operations
- makes looping over math so easy and fast!

### Add one to every element

#### hard way: doing it in a list

#### easy way: doing it with an array

### more operations

### show us the speed

In [ ]:
#make a really big array


In [ ]:
]

## Numpy ways to create arrays

#### full of zeros

#### full of ones

#### full of whatever you want 

#### a quicker way to make a range

#### an array of random integers

#### an array of random numbers from the standard distribution